# Generated by Django 3.2.9 on 2021-11-21 12:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('surname', models.CharField(max_length=30, verbose_name='name')),
                ('photo', models.ImageField(upload_to='')),
                ('about', models.TextField(max_length=500, verbose_name='professional summary')),
                ('phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='phone')),
                ('email', models.CharField(blank=True, max_length=40, null=True, verbose_name='e-mail')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='address')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='work_history', serialize=False, to='CV.person')),
                ('company', models.CharField(max_length=50, verbose_name='company name')),
                ('position', models.CharField(max_length=20, verbose_name='position')),
                ('date_start', models.DateField(verbose_name='start date')),
                ('date_finish', models.DateField(blank=True, null=True, verbose_name='finish date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='about your work')),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='skill')),
                ('person', models.ManyToManyField(to='CV.Person')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='project name')),
                ('link', models.CharField(max_length=50, null=True, verbose_name='link to project site')),
                ('description', models.TextField(max_length=500, null=True, verbose_name='description of your project')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='CV.person')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
