# Generated by Django 3.2.9 on 2021-11-21 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0004_auto_20211121_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(max_length=30, verbose_name='surname'),
        ),
        migrations.CreateModel(
            name='PersonSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CV.person')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CV.skill')),
            ],
        ),
    ]
