# Generated by Django 3.2.9 on 2021-11-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0005_auto_20211121_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='url',
            field=models.SlugField(default=1, max_length=160, unique=True),
            preserve_default=False,
        ),
    ]
