# Generated by Django 3.2.9 on 2021-11-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0006_person_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='url',
            field=models.SlugField(max_length=160),
        ),
    ]
