# Generated by Django 3.2.9 on 2021-11-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0008_alter_person_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='skill',
            field=models.ManyToManyField(blank=True, null=True, related_name='person_skill', to='CV.Skill', verbose_name='Skills'),
        ),
        migrations.AlterField(
            model_name='person',
            name='about',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Professional summary'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to="Person's photo", verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='person',
            name='url',
            field=models.SlugField(blank=True, max_length=160, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='PersonSkill',
        ),
    ]
